# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 16:48
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.CharField(help_text='Digite somente os números', max_length=20, primary_key=True, serialize=False, verbose_name='CPF')),
                ('nome', models.CharField(max_length=64)),
                ('fone', models.CharField(max_length=20, verbose_name='Telefone para contato')),
                ('login', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=36)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor total da compra')),
                ('status', models.CharField(choices=[('AP', 'Aguardando pagamento'), ('CA', 'Cancelado'), ('EA', 'Em andamento'), ('FI', 'Finalizado')], max_length=2, verbose_name='Status do pedido')),
                ('forma_pagamento', models.CharField(choices=[('BO', 'Boleto'), ('CE', 'Cartão de Crédito'), ('CD', 'Cartão de Débito'), ('TA', 'Transferência')], max_length=2, verbose_name='Método de Pagamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('rua', models.CharField(max_length=64)),
                ('bairro', models.CharField(max_length=64)),
                ('cep', models.CharField(help_text='CEP sem número', max_length=16, verbose_name='CEP')),
                ('cidade', models.CharField(max_length=64)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='store.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('nome', models.CharField(max_length=64)),
                ('cnpj', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Loja')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Compra')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço')),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('peso', models.DecimalField(decimal_places=4, help_text='Use o peso em Kg', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Categoria')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Loja')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='store.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioLoja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Loja')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Produto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Endereco', verbose_name='Endereço de entrega'),
        ),
        migrations.AddField(
            model_name='compra',
            name='produtos',
            field=models.ManyToManyField(through='store.Pedido', to='store.Produto'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Loja'),
        ),
    ]
