# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20171125_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
