# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20171125_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='produtos',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.AddField(
            model_name='produtocompra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='store.Compra'),
        ),
        migrations.AddField(
            model_name='produtocompra',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Produto'),
        ),
    ]
