# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20171126_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='valor',
        ),
    ]
