# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_compra_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='login',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
